server:
  port: 8080

spring:
  batch:
    job:
      enabled: false
    initialize-schema: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: repos
      password: root
      username: root
      authentication-database: admin
      #uri: mongodb://root:root@localhost/repos

#autoconfigure:
#exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration