server:
  port: 8080

spring:
  batch:
    job:
      enabled: true
    initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: repos
      password: root
      username: root
      authentication-database: admin
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    jdbcUrl: jdbc:mysql://localhost:3306/repos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root

  #uri: mongodb://root:root@localhost/repos

#autoconfigure:
#exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration