server:
  port: 8080

spring:
  data.mongodb:
    host: localhost
    port: 27017
    uri: mongodb://localhost/repos
    database: repos
    password: root
    username: root
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration