version: '3.7'

services:

  db:
    image: mysql:5.7
    restart: always
    container_name: 'mysql-repos'
    environment:
      MYSQL_DATABASE: repos
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'mysql_phpmyadmins'
    restart: always
    ports:
      - 80:80
    environment:
      PMA_ARBITRARY: 1
    links:
      - db