version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    container_name: 'mongodb-repos'
    environment:
      MONGO_INITDB_DATABASE: repos
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express-repos'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo